[colors.primary]
background = '#282c34'
foreground = '#abb2bf'

[colors.normal]
black   = '#1e2127'
red     = '#e06c75'
green   = '#98c379'
yellow  = '#d19a66'
blue    = '#61afef'
magenta = '#c678dd'
cyan    = '#56b6c2'
white   = '#abb2bf'

[colors.bright]
black   = '#5c6370'
red     = '#e06c75'
green   = '#98c379'
yellow  = '#d19a66'
blue    = '#61afef'
magenta = '#c678dd'
cyan    = '#56b6c2'
white   = '#ffffff'

[font]
size = 14

[font.bold]
family = "SFMono Nerd Font"
style = "Regular"

[font.bold_italic]
family = "SFMono Nerd Font"
style = "Regular Italic"

[font.italic]
family = "SFMono Nerd Font"
style = "Light Italic"

[font.normal]
family = "SFMono Nerd Font"
style = "Light"

[selection]
save_to_clipboard = true

[window]
decorations = "None"
opacity = 0.8
dynamic_padding = true

[window.padding]
x = 10
y = 10
